### ISSUE TITLE
Could Not Connect To Update Site

### ISSUE THREAD

**Issue by jmarshall0807** [sujon335/AlgebraicDatatypeTaintTracker#1]
The repo downloads and is fairly easy to set up, but when I try to run the run.sh script or the java command to use the CFG-Generator.jar I get an error saying Could Not Connect to Update Site. Without much of an error log, so I could not figure out how to fix the repo or install the necessary dependency.

**Comment by sujon335** [comment]
Could not connect to update site, refers to the inability to connect to the Amandroid Server for downloading necessary dependencies to run  Amandroid for CFG generation. 
Please try and see to setup the basic dependency of Amadroid using following link and then try running the run.sh script again. 

[http://pag.arguslab.org/argus-saf]

**Comment by jmarshall0807** [comment]
Thanks for the reply. I tried installing the correct dependencies using the link you provided and it worked. I now have amandroid setup and the command (java -jar argus-saf_***-version-assembly.jar t -o /outputPath /path/icc-bench) works fine on my machine which leads me to believe amandroid is setup correctly. However, I now get a Failed to install amandroid_stash output whenever I try to run the ./run.sh script. Do you have any idea what I may have setup incorrectly or if any other dependency is missing? I assumed that running the argus-saf***.jar would setup amandroid dependencies necessary on my machine. Thanks!
